FileVersion = 1
Dependencies = {corlib = "*", raylib-beef = "*"}

[Project]
Name = "ColdOpen"
TargetType = "BeefGUIApplication"
StartupObject = "ColdOpen.Program"

[Configs.Debug.Win64]
DebugWorkingDirectory = "c:\\Users\\weiju\\Documents\\GitHub\\cold-opens\\dist"
